const KEY='notegpt-app-v1';
const state={notes:[],selected:null,filter:'all',query:'',sort:'updated',theme:localStorage.getItem('note-theme')||'system',view:localStorage.getItem('note-view')||'list'};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function load(){try{const raw=localStorage.getItem(KEY);state.notes=raw?JSON.parse(raw):[];if(!Array.isArray(state.notes))throw Error()}catch{state.notes=[];toast('Could not read saved notes. Starting fresh.')}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state.notes))}catch{toast('Storage is full. Export notes to keep a backup.')}}
function formatDate(iso){const d=new Date(iso);const diff=Date.now()-d.getTime();if(diff<86400000)return d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});return d.toLocaleDateString([], {month:'short',day:'numeric'})}
function current(){return state.notes.find(n=>n.id===state.selected)}
function visible(){let arr=state.notes.filter(n=>{const q=state.query.toLowerCase();const matches=!q||n.title.toLowerCase().includes(q)||n.content.toLowerCase().includes(q)||n.tags.some(t=>t.toLowerCase().includes(q));const filter=state.filter==='all'||(state.filter==='favorites'&&n.isFavorite)||(state.filter==='pinned'&&n.isPinned)||(state.filter==='recent'&&(Date.now()-new Date(n.updatedAt)<604800000));return matches&&filter});return arr.sort((a,b)=>state.sort==='alpha'?a.title.localeCompare(b.title):state.sort==='created'?new Date(b.createdAt)-new Date(a.createdAt):new Date(b.updatedAt)-new Date(a.updatedAt))}
function render(){const arr=visible();$('#allCount').textContent=state.notes.length;$('#favoriteCount').textContent=state.notes.filter(n=>n.isFavorite).length;$('#pinnedCount').textContent=state.notes.filter(n=>n.isPinned).length;$('#listTitle').textContent={all:'All notes',favorites:'Favorites',pinned:'Pinned notes',recent:'Recently updated'}[state.filter];$('#listEyebrow').textContent=state.query?`Results for “${state.query}”`:'Your notebook';const list=$('#notesList');list.replaceChildren();if(!arr.length){const empty=document.createElement('div');empty.className='empty-list';empty.innerHTML='<div class="empty-icon">✎</div><h2>Your notebook is quiet</h2><p>Start with a thought, a plan, or a small list for later.</p><button class="secondary-button" id="listEmptyButton">Create your first note</button>';list.append(empty);$('#listEmptyButton').onclick=newNote;return}arr.forEach(n=>{const card=document.createElement('article');card.className=`note-card color-${n.color}${n.id===state.selected?' selected':''}`;card.onclick=()=>selectNote(n.id);const pin=n.isPinned?'<span class="card-icon pin">⌖</span>':'';const fav=n.isFavorite?'<span class="card-icon fav">♥</span>':'';card.innerHTML=`${pin}${fav}<h3>${esc(n.title||'Untitled note')}</h3><p>${esc(n.type==='checklist'?((n.checklistItems||[]).filter(i=>i.done).length)+' completed tasks':n.content||'No content yet')}</p><div class="card-meta"><span>${formatDate(n.updatedAt)}</span>${n.tags.slice(0,2).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`;list.append(card)})}
function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function selectNote(id){state.selected=id;render();openEditor();fillEditor()}
function openEditor(){$('#editorPanel').classList.add('open');$('#emptyEditor').classList.add('hidden');$('#noteForm').classList.remove('hidden')}
function newNote(){const now=new Date().toISOString();const n={id:uid(),title:'',content:'',type:'note',checklistItems:[],color:'paper',tags:[],isFavorite:false,isPinned:false,createdAt:now,updatedAt:now};state.notes.unshift(n);state.selected=n.id;persist();render();openEditor();fillEditor();$('#titleInput').focus()}
function fillEditor(){const n=current();if(!n)return;$('#titleInput').value=n.title;$('#contentInput').value=n.content;$('#dateLabel').textContent=`Updated ${formatDate(n.updatedAt)}`;$('#typeLabel').textContent=n.type==='checklist'?'Checklist':'Note';$('#pinButton').textContent=n.isPinned?'⌖':'⌖';$('#favoriteButton').textContent=n.isFavorite?'♥':'♡';$('#favoriteButton').style.color=n.isFavorite?'var(--accent)':'';$$('.type-button').forEach(b=>b.classList.toggle('active',b.dataset.type===n.type));$$('.color-dot').forEach(b=>b.classList.toggle('selected',b.dataset.color===n.color));$('#contentInput').classList.toggle('hidden',n.type==='checklist');$('#checklistEditor').classList.toggle('hidden',n.type!=='checklist');const tags=$('#tagList');tags.replaceChildren();n.tags.forEach(t=>{const s=document.createElement('span');s.className='tag';s.textContent=t;tags.append(s)});$('#wordCount').textContent=n.type==='checklist'?`${(n.checklistItems||[]).filter(i=>i.done).length}/${n.checklistItems.length} complete`:`${n.content.trim()?n.content.trim().split(/\s+/).length:0} words`;renderTasks()}
function touch(){const n=current();if(!n)return;n.title=$('#titleInput').value;n.content=$('#contentInput').value;n.updatedAt=new Date().toISOString();persist();$('#saveStatus').textContent='Saved locally';$('#dateLabel').textContent=`Updated ${formatDate(n.updatedAt)}`;render();}
function renderTasks(){const list=$('#tasksList');list.replaceChildren();const n=current();if(!n)return;(n.checklistItems||[]).forEach((item,i)=>{const row=document.createElement('div');row.className='task-row'+(item.done?' done':'');row.innerHTML=`<input type="checkbox" ${item.done?'checked':''} aria-label="Complete task"><span>${esc(item.text)}</span><button type="button" class="task-delete" aria-label="Delete task">×</button>`;row.querySelector('input').onchange=e=>{item.done=e.target.checked;touch();renderTasks();fillEditor()};row.querySelector('.task-delete').onclick=()=>{n.checklistItems.splice(i,1);touch();renderTasks();fillEditor()};list.append(row)})}
let toastTimer;function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
function closeEditor(){$('#editorPanel').classList.remove('open');state.selected=null;$('#noteForm').classList.add('hidden');$('#emptyEditor').classList.remove('hidden');render()}
function download(){const blob=new Blob([JSON.stringify(state.notes,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`note-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Notes exported')}
load();render();
$('#newNoteButton').onclick=$('#emptyNewButton').onclick=$('#fab').onclick=newNote;$('#backButton').onclick=closeEditor;$('#searchInput').oninput=e=>{state.query=e.target.value;render()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;render()};$('#filterNav').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()};$('#titleInput').oninput=$('#contentInput').oninput=touch;$('#favoriteButton').onclick=()=>{const n=current();n.isFavorite=!n.isFavorite;touch();fillEditor();toast(n.isFavorite?'Added to favorites':'Removed from favorites')};$('#pinButton').onclick=()=>{const n=current();n.isPinned=!n.isPinned;touch();toast(n.isPinned?'Note pinned':'Note unpinned')};$('#copyButton').onclick=async()=>{const n=current();const text=n.type==='checklist'?(n.checklistItems||[]).map(i=>`${i.done?'[x]':'[ ]'} ${i.text}`).join('\n'):n.content;await navigator.clipboard?.writeText(`${n.title}\n\n${text}`);toast('Note copied to clipboard')};$('#deleteButton').onclick=()=>{if(confirm('Delete this note? This cannot be undone.')){state.notes=state.notes.filter(n=>n.id!==state.selected);persist();closeEditor();toast('Note deleted')}};$$('.type-button').forEach(b=>b.onclick=()=>{const n=current();n.type=b.dataset.type;touch();fillEditor()});$('#colorPicker').onclick=e=>{const b=e.target.closest('[data-color]');if(b){current().color=b.dataset.color;touch();fillEditor()}};$('#tagInput').onkeydown=e=>{if(e.key==='Enter'&&e.target.value.trim()){current().tags.push(e.target.value.trim().slice(0,24));e.target.value='';touch();fillEditor()}};$('#addTaskButton').onclick=()=>{const v=$('#taskInput').value.trim();if(v){current().checklistItems.push({id:uid(),text:v,done:false});$('#taskInput').value='';touch();renderTasks();fillEditor()}};$('#taskInput').onkeydown=e=>{if(e.key==='Enter')$('#addTaskButton').click()};$('#shareButton').onclick=async()=>{const n=current();const text=`${n.title}\n\n${n.content}`;if(navigator.share)await navigator.share({title:n.title||'Note',text});else{await navigator.clipboard?.writeText(text);toast('Sharing unavailable, note copied instead')}};
function showSettings(){ $('#settingsModal').classList.remove('hidden');$$('.theme-options button[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===state.theme));$$('.theme-options button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}$('#settingsButton').onclick=$('#settingsTopButton').onclick=showSettings;$('#closeSettings').onclick=()=>$('#settingsModal').classList.add('hidden');$('#settingsModal').onclick=e=>{if(e.target.id==='settingsModal')$('#settingsModal').classList.add('hidden')};$$('[data-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;localStorage.setItem('note-theme',state.theme);document.body.classList.toggle('system-dark',state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches));showSettings()});$$('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;localStorage.setItem('note-view',state.view);$('#notesList').classList.toggle('grid-view',state.view==='grid');showSettings()});$('#exportButton').onclick=download;$('#importButton').onclick=()=>$('#importInput').click();$('#importInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data)||data.some(n=>!n.id||typeof n.title!=='string'))throw Error();state.notes=data.map(n=>({...n,tags:Array.isArray(n.tags)?n.tags:[],checklistItems:Array.isArray(n.checklistItems)?n.checklistItems:[]}));persist();render();toast('Notes imported')}catch{toast('That file is not a valid Note backup')}};reader.readAsText(file)};$('#deleteAllButton').onclick=()=>{if(state.notes.length&&confirm('Delete every note? This cannot be undone.')){state.notes=[];state.selected=null;persist();closeEditor();$('#settingsModal').classList.add('hidden');toast('All notes deleted')}};$('#themeButton').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('note-theme',state.theme);document.body.classList.toggle('system-dark',state.theme==='dark')};document.body.classList.toggle('system-dark',state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
