/* Note GPT: local-first application controller. */
const STORAGE_KEY = 'notegpt-app-v1';
const state = { notes: [], selectedId: null, filter: 'all', query: '', sort: 'updated', theme: localStorage.getItem('notegpt-theme') || 'system', view: localStorage.getItem('notegpt-view') || 'list' };
const $ = selector => document.querySelector(selector);
const $$ = selector => document.querySelectorAll(selector);
const uid = () => crypto.randomUUID?.() || `${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`;

function note() { return state.notes.find(item => item.id === state.selectedId); }
function safe(value) { const element = document.createElement('div'); element.textContent = value ?? ''; return element.innerHTML; }
function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => element.classList.remove('show'), 2300); }
function save() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.notes)); } catch { toast('Storage is full. Export notes to keep a backup.'); } }
function load() { try { const raw = localStorage.getItem(STORAGE_KEY); state.notes = raw ? JSON.parse(raw) : []; if (!Array.isArray(state.notes)) throw Error(); } catch { state.notes = []; toast('Could not read saved notes. Starting fresh.'); } }
function dateLabel(value) { const date = new Date(value); if (Date.now() - date.getTime() < 86400000) return date.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }); return date.toLocaleDateString([], { month: 'short', day: 'numeric' }); }

function visibleNotes() {
  const query = state.query.toLowerCase();
  const result = state.notes.filter(item => {
    const matchesQuery = !query || item.title.toLowerCase().includes(query) || item.content.toLowerCase().includes(query) || item.tags.some(tag => tag.toLowerCase().includes(query));
    const matchesFilter = state.filter === 'all' || (state.filter === 'favorites' && item.isFavorite) || (state.filter === 'pinned' && item.isPinned) || (state.filter === 'recent' && Date.now() - new Date(item.updatedAt) < 604800000);
    return matchesQuery && matchesFilter;
  });
  return result.sort((a, b) => state.sort === 'alpha' ? a.title.localeCompare(b.title) : state.sort === 'created' ? new Date(b.createdAt) - new Date(a.createdAt) : new Date(b.updatedAt) - new Date(a.updatedAt));
}

function renderList() {
  const list = $('#notesList'); const items = visibleNotes();
  const titles = { all: 'All notes', favorites: 'Favorites', pinned: 'Pinned notes', recent: 'Recently updated' };
  $('#allCount').textContent = state.notes.length; $('#favoriteCount').textContent = state.notes.filter(item => item.isFavorite).length; $('#pinnedCount').textContent = state.notes.filter(item => item.isPinned).length;
  $('#listTitle').textContent = titles[state.filter]; $('#listEyebrow').textContent = state.query ? `Results for “${state.query}”` : 'Your notebook'; list.replaceChildren();
  if (!items.length) { const empty = document.createElement('div'); empty.className = 'empty-list'; empty.innerHTML = '<div class="empty-icon">✎</div><h2>Your notebook is quiet</h2><p>Start with a thought, a plan, or a small list for later.</p><button class="secondary-button" id="listEmptyButton">Create your first note</button>'; list.append(empty); $('#listEmptyButton').onclick = create; return; }
  items.forEach(item => { const card = document.createElement('article'); const pin = item.isPinned ? '<span class="card-icon pin">⌖</span>' : ''; const favorite = item.isFavorite ? '<span class="card-icon fav">♥</span>' : ''; const preview = item.type === 'checklist' ? `${(item.checklistItems || []).filter(task => task.done).length} completed tasks` : item.content || 'No content yet'; card.className = `note-card color-${item.color}${item.id === state.selectedId ? ' selected' : ''}`; card.innerHTML = `${pin}${favorite}<h3>${safe(item.title || 'Untitled note')}</h3><p>${safe(preview)}</p><div class="card-meta"><span>${dateLabel(item.updatedAt)}</span>${item.tags.slice(0, 2).map(tag => `<span class="tag">${safe(tag)}</span>`).join('')}</div>`; card.onclick = () => select(item.id); list.append(card); });
}

function renderTasks() { const list = $('#tasksList'); const current = note(); list.replaceChildren(); if (!current) return; (current.checklistItems || []).forEach((task, index) => { const row = document.createElement('div'); row.className = `task-row${task.done ? ' done' : ''}`; row.innerHTML = `<input type="checkbox" ${task.done ? 'checked' : ''} aria-label="Complete task"><span>${safe(task.text)}</span><button type="button" class="task-delete" aria-label="Delete task">×</button>`; row.querySelector('input').onchange = event => { task.done = event.target.checked; touch(); renderTasks(); fill(); }; row.querySelector('.task-delete').onclick = () => { current.checklistItems.splice(index, 1); touch(); renderTasks(); fill(); }; list.append(row); }); }
function fill() { const current = note(); if (!current) return; $('#titleInput').value = current.title; $('#contentInput').value = current.content; $('#dateLabel').textContent = `Updated ${dateLabel(current.updatedAt)}`; $('#typeLabel').textContent = current.type === 'checklist' ? 'Checklist' : 'Note'; $('#favoriteButton').textContent = current.isFavorite ? '♥' : '♡'; $('#favoriteButton').style.color = current.isFavorite ? 'var(--accent)' : ''; $('#contentInput').classList.toggle('hidden', current.type === 'checklist'); $('#checklistEditor').classList.toggle('hidden', current.type !== 'checklist'); $$('.type-button').forEach(button => button.classList.toggle('active', button.dataset.type === current.type)); $$('.color-dot').forEach(button => button.classList.toggle('selected', button.dataset.color === current.color)); const tags = $('#tagList'); tags.replaceChildren(); current.tags.forEach(tag => { const element = document.createElement('span'); element.className = 'tag'; element.textContent = tag; tags.append(element); }); $('#wordCount').textContent = current.type === 'checklist' ? `${(current.checklistItems || []).filter(task => task.done).length}/${current.checklistItems.length} complete` : `${current.content.trim() ? current.content.trim().split(/\s+/).length : 0} words`; renderTasks(); }
function openEditor() { $('#editorPanel').classList.add('open'); $('#emptyEditor').classList.add('hidden'); $('#noteForm').classList.remove('hidden'); }
function closeEditor() { $('#editorPanel').classList.remove('open'); $('#noteForm').classList.add('hidden'); $('#emptyEditor').classList.remove('hidden'); state.selectedId = null; renderList(); }
function select(id) { state.selectedId = id; renderList(); openEditor(); fill(); }
function create() { const now = new Date().toISOString(); const current = { id: uid(), title: '', content: '', type: 'note', checklistItems: [], color: 'paper', tags: [], isFavorite: false, isPinned: false, createdAt: now, updatedAt: now }; state.notes.unshift(current); state.selectedId = current.id; save(); renderList(); openEditor(); fill(); $('#titleInput').focus(); }
function touch() { const current = note(); if (!current) return; current.title = $('#titleInput').value; current.content = $('#contentInput').value; current.updatedAt = new Date().toISOString(); save(); $('#saveStatus').textContent = 'Saved locally'; $('#dateLabel').textContent = `Updated ${dateLabel(current.updatedAt)}`; renderList(); }
function exportAll() { const blob = new Blob([JSON.stringify(state.notes, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `note-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); toast('Notes exported'); }
function applyTheme() { document.body.classList.toggle('system-dark', state.theme === 'dark' || (state.theme === 'system' && matchMedia('(prefers-color-scheme: dark)').matches)); }

function bind() {
  $('#newNoteButton').onclick = $('#emptyNewButton').onclick = $('#fab').onclick = create; $('#backButton').onclick = closeEditor; $('#searchInput').oninput = event => { state.query = event.target.value; renderList(); }; $('#sortSelect').onchange = event => { state.sort = event.target.value; renderList(); };
  $('#filterNav').onclick = event => { const button = event.target.closest('[data-filter]'); if (!button) return; state.filter = button.dataset.filter; $$('.nav-item').forEach(item => item.classList.remove('active')); button.classList.add('active'); renderList(); };
  $('#titleInput').oninput = $('#contentInput').oninput = touch;
  $('#favoriteButton').onclick = () => { const current = note(); current.isFavorite = !current.isFavorite; touch(); fill(); toast(current.isFavorite ? 'Added to favorites' : 'Removed from favorites'); };
  $('#pinButton').onclick = () => { const current = note(); current.isPinned = !current.isPinned; touch(); toast(current.isPinned ? 'Note pinned' : 'Note unpinned'); };
  $('#copyButton').onclick = async () => { const current = note(); const text = current.type === 'checklist' ? (current.checklistItems || []).map(task => `${task.done ? '[x]' : '[ ]'} ${task.text}`).join('\n') : current.content; await navigator.clipboard?.writeText(`${current.title}\n\n${text}`); toast('Note copied to clipboard'); };
  $('#deleteButton').onclick = () => { if (confirm('Delete this note? This cannot be undone.')) { state.notes = state.notes.filter(item => item.id !== state.selectedId); save(); closeEditor(); toast('Note deleted'); } };
  $$('.type-button').forEach(button => button.onclick = () => { note().type = button.dataset.type; touch(); fill(); }); $('#colorPicker').onclick = event => { const button = event.target.closest('[data-color]'); if (button) { note().color = button.dataset.color; touch(); fill(); } };
  $('#tagInput').onkeydown = event => { if (event.key === 'Enter' && event.target.value.trim()) { note().tags.push(event.target.value.trim().slice(0, 24)); event.target.value = ''; touch(); fill(); } }; $('#addTaskButton').onclick = () => { const value = $('#taskInput').value.trim(); if (value) { note().checklistItems.push({ id: uid(), text: value, done: false }); $('#taskInput').value = ''; touch(); fill(); } }; $('#taskInput').onkeydown = event => { if (event.key === 'Enter') $('#addTaskButton').click(); };
  $('#shareButton').onclick = async () => { const current = note(); const text = `${current.title}\n\n${current.content}`; if (navigator.share) await navigator.share({ title: current.title || 'Note', text }); else { await navigator.clipboard?.writeText(text); toast('Sharing unavailable, note copied instead'); } };
  $('#settingsButton').onclick = $('#settingsTopButton').onclick = () => $('#settingsModal').classList.remove('hidden'); $('#closeSettings').onclick = () => $('#settingsModal').classList.add('hidden'); $('#settingsModal').onclick = event => { if (event.target.id === 'settingsModal') $('#settingsModal').classList.add('hidden'); };
  $$('[data-theme]').forEach(button => button.onclick = () => { state.theme = button.dataset.theme; localStorage.setItem('notegpt-theme', state.theme); applyTheme(); }); $$('[data-view]').forEach(button => button.onclick = () => { state.view = button.dataset.view; localStorage.setItem('notegpt-view', state.view); $('#notesList').classList.toggle('grid-view', state.view === 'grid'); }); $('#exportButton').onclick = exportAll; $('#importButton').onclick = () => $('#importInput').click(); $('#deleteAllButton').onclick = () => { if (state.notes.length && confirm('Delete every note? This cannot be undone.')) { state.notes = []; state.selectedId = null; save(); closeEditor(); $('#settingsModal').classList.add('hidden'); toast('All notes deleted'); } }; $('#themeButton').onclick = () => { state.theme = state.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('notegpt-theme', state.theme); applyTheme(); };
  $('#importInput').onchange = event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const data = JSON.parse(reader.result); if (!Array.isArray(data) || data.some(item => !item.id || typeof item.title !== 'string')) throw Error(); state.notes = data.map(item => ({ ...item, tags: Array.isArray(item.tags) ? item.tags : [], checklistItems: Array.isArray(item.checklistItems) ? item.checklistItems : [] })); save(); renderList(); toast('Notes imported'); } catch { toast('That file is not a valid Note backup'); } }; reader.readAsText(file); };
}

load(); bind(); applyTheme(); renderList();
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js', { scope: './' }).catch(() => {}));
