/* Note GPT: local-first application controller. */
const STORAGE_KEY = 'notegpt-app-v1';
const state = { notes: [], selectedId: null, filter: 'all', query: '', sort: 'updated', theme: localStorage.getItem('notegpt-theme') || 'system', view: localStorage.getItem('notegpt-view') || 'list' };
const $ = selector => document.querySelector(selector);
const $$ = selector => document.querySelectorAll(selector);
const uid = () => crypto.randomUUID?.() || `${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`;

function note() { return state.notes.find(item => item.id === state.selectedId); }
function safe(value) { const element = document.createElement('div'); element.textContent = value ?? ''; return element.innerHTML; }
function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => element.classList.remove('show'), 2300); }
function save() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.notes)); } catch { toast('Storage is full. Export notes to keep a backup.'); } }
function load() { try { const raw = localStorage.getItem(STORAGE_KEY); state.notes = raw ? JSON.parse(raw) : []; if (!Array.isArray(state.notes)) throw Error(); state.notes = state.notes.map(item => ({ ...item, deletedAt: item.deletedAt || null, isArchived: Boolean(item.isArchived), direction: item.direction || 'auto' })); } catch { state.notes = []; toast('Could not read saved notes. Starting fresh.'); } }
function dateLabel(value) { const date = new Date(value); if (Date.now() - date.getTime() < 86400000) return date.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }); return date.toLocaleDateString([], { month: 'short', day: 'numeric' }); }

function visibleNotes() {
  const query = state.query.toLowerCase();
  const result = state.notes.filter(item => {
    const matchesQuery = !query || item.title.toLowerCase().includes(query) || item.content.toLowerCase().includes(query) || item.tags.some(tag => tag.toLowerCase().includes(query));
    const active = !item.deletedAt && !item.isArchived;
    const matchesFilter = state.filter === 'all' && active || (state.filter === 'favorites' && item.isFavorite && active) || (state.filter === 'pinned' && item.isPinned && active) || (state.filter === 'recent' && Date.now() - new Date(item.updatedAt) < 604800000 && active) || (state.filter === 'archived' && item.isArchived && !item.deletedAt) || (state.filter === 'trash' && item.deletedAt);
    return matchesQuery && matchesFilter;
  });
  return result.sort((a, b) => state.sort === 'alpha' ? a.title.localeCompare(b.title) : state.sort === 'created' ? new Date(b.createdAt) - new Date(a.createdAt) : new Date(b.updatedAt) - new Date(a.updatedAt));
}

function renderList() {
  const list = $('#notesList'); const items = visibleNotes();
  const titles = { all: 'All notes', favorites: 'Favorites', pinned: 'Pinned notes', recent: 'Recently updated', archived: 'Archived', trash: 'Trash' };
  $('#allCount').textContent = state.notes.filter(item => !item.deletedAt && !item.isArchived).length; $('#favoriteCount').textContent = state.notes.filter(item => item.isFavorite && !item.deletedAt && !item.isArchived).length; $('#pinnedCount').textContent = state.notes.filter(item => item.isPinned && !item.deletedAt && !item.isArchived).length; $('#archivedCount').textContent = state.notes.filter(item => item.isArchived && !item.deletedAt).length; $('#trashCount').textContent = state.notes.filter(item => item.deletedAt).length;
  $('#listTitle').textContent = titles[state.filter]; $('#listEyebrow').textContent = state.query ? `Results for “${state.query}”` : 'Your notebook'; list.replaceChildren();
  if (!items.length) { const empty = document.createElement('div'); empty.className = 'empty-list'; empty.innerHTML = '<div class="empty-icon">✎</div><h2>Your notebook is quiet</h2><p>Start with a thought, a plan, or a small list for later.</p><button class="secondary-button" id="listEmptyButton">Create your first note</button>'; list.append(empty); $('#listEmptyButton').onclick = create; return; }
  items.forEach(item => { const card = document.createElement('article'); const pin = item.isPinned ? '<span class="card-icon pin">⌖</span>' : ''; const favorite = item.isFavorite ? '<span class="card-icon fav">♥</span>' : ''; const preview = item.type === 'checklist' ? `${(item.checklistItems || []).filter(task => task.done).length} completed tasks` : item.content || 'No content yet'; card.className = `note-card color-${item.color}${item.id === state.selectedId ? ' selected' : ''}`; card.innerHTML = `${pin}${favorite}<h3>${safe(item.title || 'Untitled note')}</h3><p>${safe(preview)}</p><div class="card-meta"><span>${dateLabel(item.updatedAt)}</span>${item.tags.slice(0, 2).map(tag => `<span class="tag">${safe(tag)}</span>`).join('')}</div>`; card.onclick = () => select(item.id); list.append(card); });
}

function renderTasks() { const list = $('#tasksList'); const current = note(); list.replaceChildren(); if (!current) return; (current.checklistItems || []).forEach((task, index) => { const row = document.createElement('div'); row.className = `task-row${task.done ? ' done' : ''}`; row.innerHTML = `<input type="checkbox" ${task.done ? 'checked' : ''} aria-label="Complete task"><span>${safe(task.text)}</span><button type="button" class="task-delete" aria-label="Delete task">×</button>`; row.querySelector('input').onchange = event => { task.done = event.target.checked; touch(); renderTasks(); fill(); }; row.querySelector('.task-delete').onclick = () => { current.checklistItems.splice(index, 1); touch(); renderTasks(); fill(); }; list.append(row); }); }
function fill() { const current = note(); if (!current) return; $('#titleInput').value = current.title; $('#contentInput').value = current.content; $('#dateLabel').textContent = `Updated ${dateLabel(current.updatedAt)}`; $('#typeLabel').textContent = current.type === 'checklist' ? 'Checklist' : 'Note'; $('#favoriteButton').textContent = current.isFavorite ? '♥' : '♡'; $('#favoriteButton').style.color = current.isFavorite ? 'var(--accent)' : ''; $('#contentInput').classList.toggle('hidden', current.type === 'checklist'); $('#checklistEditor').classList.toggle('hidden', current.type !== 'checklist'); $$('.type-button').forEach(button => button.classList.toggle('active', button.dataset.type === current.type)); $$('.color-dot').forEach(button => button.classList.toggle('selected', button.dataset.color === current.color)); const tags = $('#tagList'); tags.replaceChildren(); current.tags.forEach(tag => { const element = document.createElement('span'); element.className = 'tag'; element.textContent = tag; tags.append(element); }); $('#wordCount').textContent = current.type === 'checklist' ? `${(current.checklistItems || []).filter(task => task.done).length}/${current.checklistItems.length} complete` : `${current.content.trim() ? current.content.trim().split(/\s+/).length : 0} words`; renderTasks(); }
function openEditor() { $('#editorPanel').classList.add('open'); $('#emptyEditor').classList.add('hidden'); $('#noteForm').classList.remove('hidden'); }
function closeEditor() { $('#editorPanel').classList.remove('open'); $('#noteForm').classList.add('hidden'); $('#emptyEditor').classList.remove('hidden'); state.selectedId = null; renderList(); }
function select(id) { state.selectedId = id; renderList(); openEditor(); fill(); if ($('#directionSelect')) $('#directionSelect').value = note().direction || 'auto'; renderDrawing(); }
function create() { const now = new Date().toISOString(); const current = { id: uid(), title: '', content: '', type: 'note', checklistItems: [], color: 'paper', tags: [], isFavorite: false, isPinned: false, direction: 'auto', drawing: '', createdAt: now, updatedAt: now }; state.notes.unshift(current); state.selectedId = current.id; save(); renderList(); openEditor(); fill(); if ($('#directionSelect')) $('#directionSelect').value = 'auto'; renderDrawing(); $('#titleInput').focus(); }
function touch() { const current = note(); if (!current) return; current.title = $('#titleInput').value; current.content = $('#contentInput').value; current.updatedAt = new Date().toISOString(); save(); $('#saveStatus').textContent = 'Saved locally'; $('#dateLabel').textContent = `Updated ${dateLabel(current.updatedAt)}`; renderList(); }
function exportAll() { const blob = new Blob([JSON.stringify(state.notes, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `note-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); toast('Notes exported'); }
function downloadExport(filename, content, type) { const blob = new Blob([content], { type }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); toast('Export complete'); }
function exportMarkdown() { const content = state.notes.map(item => `# ${item.title || 'Untitled note'}\n\n${item.type === 'checklist' ? (item.checklistItems || []).map(task => `- [${task.done ? 'x' : ' '}] ${task.text}`).join('\n') : item.content}\n\nTags: ${item.tags.join(', ') || 'None'}\n`).join('\n---\n\n'); downloadExport('note-export.md', content, 'text/markdown'); }
function exportText() { const content = state.notes.map(item => `${item.title || 'Untitled note'}\n${'='.repeat((item.title || 'Untitled note').length)}\n${item.type === 'checklist' ? (item.checklistItems || []).map(task => `${task.done ? '[x]' : '[ ]'} ${task.text}`).join('\n') : item.content}\n`).join('\n\n'); downloadExport('note-export.txt', content, 'text/plain'); }
function applyTheme() { document.body.classList.toggle('system-dark', state.theme === 'dark' || (state.theme === 'system' && matchMedia('(prefers-color-scheme: dark)').matches)); }
function ensureDirectionControl() { const options = document.querySelector('.editor-options'); if (!options || $('#directionSelect')) return; const select = document.createElement('select'); select.id = 'directionSelect'; select.setAttribute('aria-label', 'Text direction'); select.innerHTML = '<option value="auto">Auto direction</option><option value="ltr">Left to right</option><option value="rtl">Right to left</option>'; select.onchange = event => { const current = note(); if (!current) return; current.direction = event.target.value; $('#titleInput').dir = current.direction; $('#contentInput').dir = current.direction; save(); toast(current.direction === 'rtl' ? 'Right-to-left writing enabled' : current.direction === 'ltr' ? 'Left-to-right writing enabled' : 'Automatic direction enabled'); }; options.append(select); }
function ensureDrawingEditor() { const host = $('#drawingEditor'); if (!host || host.dataset.ready) return; host.dataset.ready = 'true'; host.innerHTML = '<div class="drawing-toolbar"><label>Drawing <input id="drawingColor" type="color" value="#2d7258" aria-label="Drawing color"></label><button type="button" class="secondary-button" id="clearDrawing">Clear drawing</button></div><canvas id="drawingCanvas" width="900" height="300" aria-label="Drawing canvas"></canvas>'; const canvas = $('#drawingCanvas'); const context = canvas.getContext('2d'); let drawing = false; const point = event => { const rect = canvas.getBoundingClientRect(); return [(event.clientX - rect.left) * canvas.width / rect.width, (event.clientY - rect.top) * canvas.height / rect.height]; }; canvas.onpointerdown = event => { drawing = true; canvas.setPointerCapture(event.pointerId); const [x, y] = point(event); context.beginPath(); context.moveTo(x, y); }; canvas.onpointermove = event => { if (!drawing) return; const [x, y] = point(event); context.strokeStyle = $('#drawingColor').value; context.lineWidth = 4; context.lineCap = 'round'; context.lineTo(x, y); context.stroke(); }; canvas.onpointerup = () => { drawing = false; const current = note(); if (current) { current.drawing = canvas.toDataURL('image/png'); save(); } }; $('#clearDrawing').onclick = () => { context.clearRect(0, 0, canvas.width, canvas.height); const current = note(); if (current) { current.drawing = ''; save(); } toast('Drawing cleared'); }; }
function renderDrawing() { const current = note(); const canvas = $('#drawingCanvas'); if (!current || !canvas) return; const context = canvas.getContext('2d'); context.clearRect(0, 0, canvas.width, canvas.height); if (current.drawing) { const image = new Image(); image.onload = () => context.drawImage(image, 0, 0); image.src = current.drawing; } }
function improveDrawingControls() { const canvas = $('#drawingCanvas'); const input = $('#drawingColor'); if (canvas) { canvas.height = 560; canvas.style.height = '420px'; } if (input) { input.hidden = true; const host = input.parentElement; const swatches = document.createElement('div'); swatches.className = 'drawing-swatches'; ['#2d7258', '#d85f57', '#d69b32', '#4d83b6', '#252b2a'].forEach(color => { const button = document.createElement('button'); button.type = 'button'; button.className = 'drawing-swatch'; button.style.background = color; button.setAttribute('aria-label', `Drawing color ${color}`); button.onclick = () => { input.value = color; }; swatches.append(button); }); host.parentElement.insertBefore(swatches, host); } const picker = $('#colorPicker'); if (picker) picker.addEventListener('click', event => { const button = event.target.closest('[data-color]'); const current = note(); if (!button || !current) return; const colors = { paper: '#202623', mint: '#2d7258', peach: '#b55735', lavender: '#765aa6', sky: '#24628b' }; current.textColor = colors[button.dataset.color]; $('#titleInput').style.color = current.textColor; $('#contentInput').style.color = current.textColor; save(); }); }
function sanitizeRichHtml(html) { const template = document.createElement('template'); template.innerHTML = html; template.content.querySelectorAll('script,style,iframe,object,embed').forEach(element => element.remove()); template.content.querySelectorAll('*').forEach(element => { [...element.attributes].forEach(attribute => { if (attribute.name.toLowerCase().startsWith('on')) element.removeAttribute(attribute.name); }); }); return template.innerHTML; }
function ensureRichEditor() { const host = $('#richEditor'); if (!host || host.dataset.ready) return; host.dataset.ready = 'true'; const toolbar = document.createElement('div'); toolbar.className = 'rich-toolbar'; toolbar.innerHTML = '<button type="button" data-command="bold" aria-label="Bold"><strong>B</strong></button><button type="button" data-command="italic" aria-label="Italic"><em>I</em></button><button type="button" data-command="insertUnorderedList" aria-label="Bullet list">•</button><button type="button" data-command="formatBlock" data-value="h3" aria-label="Heading">H</button><span class="rich-colors"></span><button type="button" id="plainModeButton">Plain text</button>'; const editor = document.createElement('div'); editor.id = 'richContent'; editor.contentEditable = 'true'; editor.setAttribute('role', 'textbox'); editor.setAttribute('aria-label', 'Formatted note content'); host.append(toolbar, editor); toolbar.querySelectorAll('[data-command]').forEach(button => button.onclick = () => { editor.focus(); document.execCommand(button.dataset.command, false, button.dataset.value || null); syncRichContent(); }); const colors = ['#2d7258', '#d85f57', '#d69b32', '#4d83b6', '#252b2a']; colors.forEach(color => { const button = document.createElement('button'); button.type = 'button'; button.className = 'rich-color'; button.style.background = color; button.setAttribute('aria-label', `Text color ${color}`); button.onclick = () => { editor.focus(); document.execCommand('foreColor', false, color); syncRichContent(); }; toolbar.querySelector('.rich-colors').append(button); }); editor.oninput = syncRichContent; $('#plainModeButton').onclick = () => { $('#contentInput').classList.remove('hidden'); host.classList.add('hidden'); }; }
function syncRichContent() { const current = note(); const editor = $('#richContent'); if (!current || !editor) return; current.contentHtml = sanitizeRichHtml(editor.innerHTML); current.content = editor.innerText; current.updatedAt = new Date().toISOString(); save(); $('#saveStatus').textContent = 'Saved locally'; renderList(); }
function openRichEditor() { const current = note(); if (!current || !$('#richContent')) return; $('#richContent').innerHTML = sanitizeRichHtml(current.contentHtml || safe(current.content).replace(/\n/g, '<br>')); $('#contentInput').classList.add('hidden'); $('#richEditor').classList.remove('hidden'); }
function ensureRichToggle() { const options = document.querySelector('.editor-options'); if (!options || $('#richModeButton')) return; const button = document.createElement('button'); button.type = 'button'; button.id = 'richModeButton'; button.className = 'secondary-button'; button.textContent = 'Format text'; button.onclick = openRichEditor; options.append(button); }
function improveDirectionControls() { const select = $('#directionSelect'); if (!select || $('#directionButtons')) return; select.hidden = true; const group = document.createElement('div'); group.id = 'directionButtons'; group.className = 'direction-buttons'; const ltr = document.createElement('button'); const rtl = document.createElement('button'); ltr.type = rtl.type = 'button'; ltr.className = rtl.className = 'direction-button'; ltr.textContent = '⇥'; rtl.textContent = '⇤'; ltr.title = 'Left to right'; rtl.title = 'Right to left'; ltr.setAttribute('aria-label', 'Left to right'); rtl.setAttribute('aria-label', 'Right to left'); const choose = direction => { select.value = direction; select.dispatchEvent(new Event('change')); ltr.classList.toggle('active', direction === 'ltr'); rtl.classList.toggle('active', direction === 'rtl'); }; ltr.onclick = () => choose('ltr'); rtl.onclick = () => choose('rtl'); group.append(ltr, rtl); select.parentElement.append(group); }
function ensureArchiveButton() { const actions = document.querySelector('.editor-actions'); if (!actions || $('#archiveButton')) return; const button = document.createElement('button'); button.type = 'button'; button.id = 'archiveButton'; button.className = 'toolbar-button'; button.setAttribute('aria-label', 'Archive note'); button.textContent = '▣'; actions.insertBefore(button, $('#restoreButton') || $('#deleteButton')); button.onclick = () => { const current = note(); if (!current || current.deletedAt) return; current.isArchived = !current.isArchived; save(); renderList(); fill(); toast(current.isArchived ? 'Note archived' : 'Note restored to notebook'); }; }
function ensureDuplicateButton() { const actions = document.querySelector('.editor-actions'); if (!actions || $('#duplicateButton')) return; const button = document.createElement('button'); button.type = 'button'; button.id = 'duplicateButton'; button.className = 'toolbar-button'; button.setAttribute('aria-label', 'Duplicate note'); button.textContent = '＋'; actions.insertBefore(button, $('#archiveButton') || $('#restoreButton') || $('#deleteButton')); button.onclick = () => { const current = note(); if (!current || current.deletedAt) return; const now = new Date().toISOString(); const copy = { ...current, id: uid(), title: `${current.title || 'Untitled note'} copy`, checklistItems: (current.checklistItems || []).map(task => ({ ...task, id: uid() })), tags: [...current.tags], isFavorite: false, isPinned: false, isArchived: false, deletedAt: null, createdAt: now, updatedAt: now }; state.notes.unshift(copy); state.selectedId = copy.id; save(); renderList(); fill(); toast('Note duplicated'); }; }
function ensureRestoreButton() { const actions = document.querySelector('.editor-actions'); if (!actions || $('#restoreButton')) return; const button = document.createElement('button'); button.type = 'button'; button.id = 'restoreButton'; button.className = 'toolbar-button'; button.setAttribute('aria-label', 'Restore note'); button.textContent = '↶'; actions.insertBefore(button, $('#deleteButton')); button.onclick = () => { const current = note(); current.deletedAt = null; save(); renderList(); fill(); toast('Note restored'); }; }

function bind() {
  ensureDirectionControl(); ensureDrawingEditor();
  document.addEventListener('keydown', event => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'n') { event.preventDefault(); create(); } });
  const dataGroup = $('#exportButton')?.parentElement; if (dataGroup && !$('#exportMarkdownButton')) { const markdown = document.createElement('button'); markdown.className = 'setting-action'; markdown.id = 'exportMarkdownButton'; markdown.innerHTML = 'Export as Markdown <span>→</span>'; markdown.onclick = exportMarkdown; const text = document.createElement('button'); text.className = 'setting-action'; text.id = 'exportTextButton'; text.innerHTML = 'Export as plain text <span>→</span>'; text.onclick = exportText; dataGroup.insertBefore(markdown, $('#importButton')); dataGroup.insertBefore(text, $('#importButton')); }
  $('#newNoteButton').onclick = $('#emptyNewButton').onclick = $('#fab').onclick = create; $('#backButton').onclick = closeEditor; $('#searchInput').oninput = event => { state.query = event.target.value; renderList(); }; $('#sortSelect').onchange = event => { state.sort = event.target.value; renderList(); };
  $('#filterNav').onclick = event => { const button = event.target.closest('[data-filter]'); if (!button) return; state.filter = button.dataset.filter; $$('.nav-item').forEach(item => item.classList.remove('active')); button.classList.add('active'); renderList(); };
  $('#titleInput').oninput = $('#contentInput').oninput = touch;
  $('#favoriteButton').onclick = () => { const current = note(); current.isFavorite = !current.isFavorite; touch(); fill(); toast(current.isFavorite ? 'Added to favorites' : 'Removed from favorites'); };
  $('#pinButton').onclick = () => { const current = note(); current.isPinned = !current.isPinned; touch(); toast(current.isPinned ? 'Note pinned' : 'Note unpinned'); };
  $('#copyButton').onclick = async () => { const current = note(); const text = current.type === 'checklist' ? (current.checklistItems || []).map(task => `${task.done ? '[x]' : '[ ]'} ${task.text}`).join('\n') : current.content; await navigator.clipboard?.writeText(`${current.title}\n\n${text}`); toast('Note copied to clipboard'); };
  $('#deleteButton').onclick = () => { const current = note(); if (!current) return; if (current.deletedAt) { if (confirm('Delete this note permanently? This cannot be undone.')) { state.notes = state.notes.filter(item => item.id !== state.selectedId); save(); closeEditor(); toast('Note permanently deleted'); } } else if (confirm('Move this note to Trash?')) { current.deletedAt = new Date().toISOString(); save(); closeEditor(); toast('Note moved to Trash'); } };
  ensureRestoreButton();
  ensureArchiveButton();
  ensureDuplicateButton();
  $$('.type-button').forEach(button => button.onclick = () => { note().type = button.dataset.type; touch(); fill(); }); $('#colorPicker').onclick = event => { const button = event.target.closest('[data-color]'); if (button) { note().color = button.dataset.color; touch(); fill(); } };
  $('#tagInput').onkeydown = event => { if (event.key === 'Enter' && event.target.value.trim()) { note().tags.push(event.target.value.trim().slice(0, 24)); event.target.value = ''; touch(); fill(); } }; $('#addTaskButton').onclick = () => { const value = $('#taskInput').value.trim(); if (value) { note().checklistItems.push({ id: uid(), text: value, done: false }); $('#taskInput').value = ''; touch(); fill(); } }; $('#taskInput').onkeydown = event => { if (event.key === 'Enter') $('#addTaskButton').click(); };
  $('#shareButton').onclick = async () => { const current = note(); const text = `${current.title}\n\n${current.content}`; if (navigator.share) await navigator.share({ title: current.title || 'Note', text }); else { await navigator.clipboard?.writeText(text); toast('Sharing unavailable, note copied instead'); } };
  $('#settingsButton').onclick = $('#settingsTopButton').onclick = () => $('#settingsModal').classList.remove('hidden'); $('#closeSettings').onclick = () => $('#settingsModal').classList.add('hidden'); $('#settingsModal').onclick = event => { if (event.target.id === 'settingsModal') $('#settingsModal').classList.add('hidden'); };
  $$('[data-theme]').forEach(button => button.onclick = () => { state.theme = button.dataset.theme; localStorage.setItem('notegpt-theme', state.theme); applyTheme(); }); $$('[data-view]').forEach(button => button.onclick = () => { state.view = button.dataset.view; localStorage.setItem('notegpt-view', state.view); $('#notesList').classList.toggle('grid-view', state.view === 'grid'); }); $('#exportButton').onclick = exportAll; $('#importButton').onclick = () => $('#importInput').click(); $('#deleteAllButton').onclick = () => { if (state.notes.length && confirm('Delete every note? This cannot be undone.')) { state.notes = []; state.selectedId = null; save(); closeEditor(); $('#settingsModal').classList.add('hidden'); toast('All notes deleted'); } }; $('#themeButton').onclick = () => { state.theme = state.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('notegpt-theme', state.theme); applyTheme(); };
  $('#importInput').onchange = event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const data = JSON.parse(reader.result); if (!Array.isArray(data) || data.some(item => !item.id || typeof item.title !== 'string')) throw Error(); state.notes = data.map(item => ({ ...item, tags: Array.isArray(item.tags) ? item.tags : [], checklistItems: Array.isArray(item.checklistItems) ? item.checklistItems : [], isFavorite: Boolean(item.isFavorite), isPinned: Boolean(item.isPinned), deletedAt: item.deletedAt || null, isArchived: Boolean(item.isArchived) })); save(); renderList(); toast('Notes imported'); } catch { toast('That file is not a valid Note backup'); } }; reader.readAsText(file); };
}

load(); bind(); ensureRichEditor(); ensureRichToggle(); improveDrawingControls(); improveDirectionControls(); applyTheme(); renderList();
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js', { scope: './' }).catch(() => {}));
